services:
  - type: web
    name: ocr-project
    env: python
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr
      pip install -r requirements.txt
    startCommand: gunicorn ocr_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ocr_project.settings
      - key: PYTHON_VERSION
        value: 3.10
