services:
  - type: web
    name: ocr-project
    env: python
    region: oregon  # or frankfurt/london if you're closer to Europe/Africa

    buildCommand: |
      apt-get update && \
      apt-get install -y tesseract-ocr libtesseract-dev libleptonica-dev pkg-config poppler-utils && \
      pip install --upgrade pip && \
      pip install -r requirements.txt

    startCommand: gunicorn ocr_project.wsgi:application

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ocr_project.settings
      - key: PYTHON_VERSION
        value: 3.10
      - key: SECRET_KEY
        sync: false  # Add this in Render dashboard manually for security
      - key: DEBUG
        value: 'False'
