services:
  - type: web
    name: ocr-project
    env: python
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr
      pip install -r requirements.txt
    startCommand: gunicorn ocr_project.wsgi
    region: oregon
    plan: free
